apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQWQyZ0F3SUJBZ0lSQU45SjRHMisya3dYb3FvTzZLSEtYQ2t3RFFZSktvWklodmNOQVFFTEJRQXcKSWpFZ01CNEdBMVVFQXd3WGEzVmlaWEp1WlhSbGN5MWpiSFZ6ZEdWeUxUZzVNemt3SGhjTk1qTXhNakU0TWpBdwpPREV3V2hjTk1qZ3hNakUzTWpBd09ERXdXakFpTVNBd0hnWURWUVFEREJkcmRXSmxjbTVsZEdWekxXTnNkWE4wClpYSXRPRGt6T1RDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTmlWNUNNNm5VUmUKQ3VMc3JqLzlGcUg4UVVNTFBtSnJPVjUrVWgvczYyR3VpcWxkYzIwWXJzemxIVzd4NFF5OU1xeW5DM1hYNE4rdgovVFhTcU9DTlJHK3NRblBBakg4OUIyZFhINmljdVJHUGVvUVlwM3dOa3AvRWx2VnV3WTJoM2tyeXgvZytob1NEClN3ZDRpZHJHdEF2OEptMTJVOER3L0NHQzNvby9yYytsaHl1ZnU0Z09RTDhjb2JtZkxmRUNXN3k3dXBYeDZZcVAKYkFUMmtkbXdvMDA5UlRaSHpPK1FZTk84dE1iVGtsSWZhY3RBblVDVnBJRFZDYVFuVStGODRuZ2x5U1dKaUhVRwpKUHQwNnY2Wm5CZFUxSlpyZ1NCZExFa000SDdldTVKTFRUNDY0d0F6U2s3czBQdjRKVmhBNEhYeTMwN2YyK2k4ClpzVGlMRjRoZ3RzQ0F3RUFBYU1tTUNRd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFEQU9CZ05WSFE4QkFmOEUKQkFNQ0FnUXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSURKSSs0UWZPTHkySXVWMnIwZ2JvQjYrTE5GSW9jRgpmNlMzOHVYQ0l6TWdTcEcxWGIyTnBVbVNEbnUzTzN3a1N1UnU2UWVvZ3hWUDBWYmZ4SGc1TWsyUmh4K0FxRU9nCmd2OWxzV3JmKzFsSUJkWEl0VmpBY0tEaURMbU5QVzR5TytQdkhyTXRYdkQxLzhGL3pqbjBKaWRnSXVjUkJQdVoKdVdHZEFaVGZVQml4UHJaTTZZVWtOUlZYc1hJVWpzNXRTT2FlZXhZMnNhNVBzU2VJeVg4N3dWeTBDcXY1TERGKwp0RUNmVjRyTjFRd1hKTmFKT0oxSVF2b1FFdHh2TlAzVHhjWGFqQkhucmhZL3I0cTJ0d0o1dmpMTzF3cEUyc0N0CmpndTBXMll6TWw5SWFValBQSjZSNUtmRUhMaDI0RUtNaXhLSVI2UTBOcTVKMGEvQStZTHV4YkE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://95.163.250.78:6443
  name: kubernetes-cluster-8939
contexts:
- context:
    cluster: kubernetes-cluster-8939
    user: kubernetes-cluster-8939
  name: default/kubernetes-cluster-8939
current-context: default/kubernetes-cluster-8939
kind: Config
preferences: {}
users:
- name: kubernetes-cluster-8939
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: client-keystone-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://infra.mail.ru:35357/v3/"
      - name: "OS_USERNAME"
        value: "team@growth-tech.ru"
      #- name: "OS_PASSWORD"
      #  value: "put your password here"
      - name: "OS_PROJECT_ID"
        value: "5817d480b66c4fdda77b318b394dfe33"
      - name: "OS_DOMAIN_NAME"
        value: "users"
      interactiveMode: IfAvailable
      provideClusterInfo: false